TEMPLATE_STATUS_SUCCESS = 0
TEMPLATE_STATUS_NOT_A_TEMPLATE = 1
TEMPLATE_STATUS_DUP_TAGS = 2

RUNNER_CONFIG_KEY_SCRIPT_FILE = 'xx_script file'.freeze
RUNNER_CONFIG_KEY_OUTPUT_FOLDER = 'xx_output folder'.freeze
RUNNER_CONFIG_KEY_OUTPUT_BASE_NAME = 'xx_output file base name'.freeze
RUNNER_CONFIG_KEY_SOURCE_FILE = 'xx_source file'.freeze
