
development:

  path_to_runner_script: <%= Rails.root.to_s + '/bin/illustrator_processing/run_AI_script.rb' %>
  path_to_extract_tags_script: <%= Rails.root.to_s + '/bin/illustrator_processing/extractTags.jsx' %>
  path_to_extract_images_script: <%= Rails.root.to_s + '/bin/illustrator_processing/extractImages.jsx' %>
  path_to_post_process_script: <%= Rails.root.to_s + '/bin/illustrator_processing/postProcess.jsx' %>
  path_to_extract_all_text_script: <%= Rails.root.to_s + '/bin/illustrator_processing/extractAllText.jsx' %>
  path_to_search_replace_script: <%= Rails.root.to_s + '/bin/illustrator_processing/searchAndReplace.jsx' %>
  path_to_image_search_replace_script: <%= Rails.root.to_s + '/bin/illustrator_processing/searchAndReplaceImages.jsx' %>
  path_to_split_text_script: <%= Rails.root.to_s + '/bin/illustrator_processing/splitText.jsx' %>
  path_to_quick_version_root: <%= Rails.root.to_s + '/working/versions/' %>
  path_to_versions_folder: <%= Rails.root.to_s + '/public/system/versions/' %>
  path_to_collage_root: <%= Rails.root.to_s + '/working/collages/' %>
  path_to_zombie_templates_root: <%= Rails.root.to_s + '/working/zombies/design_templates/' %>
  path_to_text_processing_folder: <%= Rails.root.to_s + '/working/text_processing/' %>
  path_to_remote_render_folder_root: <%= '/Volumes/krucible/Users/bombsheller/BombshellerGoogleDrive/Chasma/NEW_DESIGNS/ForCatalog/' %>
  path_to_local_render_folder_root: <%= Rails.root.to_s + '/public/RENDERINGS/' %>

  run_remotely: false
  remote_server_uri: 'http://localhost:3000'

  collages_max_items_to_retrieve: 25
  collages_min_width_pixels: 500
  collages_min_height_pixels: 500


test:

  path_to_runner_script: <%= Rails.root.to_s + '/bin/illustrator_processing/run_AI_script.rb' %>
  path_to_extract_tags_script: <%= Rails.root.to_s + '/bin/illustrator_processing/extractTags.jsx' %>
  path_to_extract_images_script: <%= Rails.root.to_s + '/bin/illustrator_processing/extractImages.jsx' %>
  path_to_post_process_script: <%= Rails.root.to_s + '/bin/illustrator_processing/postProcess.jsx' %>
  path_to_extract_all_text_script: <%= Rails.root.to_s + '/bin/illustrator_processing/extractAllText.jsx' %>
  path_to_search_replace_script: <%= Rails.root.to_s + '/bin/illustrator_processing/searchAndReplace.jsx' %>
  path_to_image_search_replace_script: <%= Rails.root.to_s + '/bin/illustrator_processing/searchAndReplaceImages.jsx' %>
  path_to_split_text_script: <%= Rails.root.to_s + '/bin/illustrator_processing/splitText.jsx' %>
  path_to_quick_version_root: <%= Rails.root.to_s + '/working/test_versions/' %>
  path_to_versions_folder: <%= Rails.root.to_s + '/public/system/test_versions/' %>
  path_to_collage_root: <%= Rails.root.to_s + '/working/test_collages/' %>
  path_to_zombie_templates_root: <%= Rails.root.to_s + '/working/zombies/design_templates/' %>
  path_to_text_processing_folder: <%= Rails.root.to_s + '/working/text_processing/' %>
  path_to_remote_render_folder_root: <%= '/Volumes/krucible/Users/bombsheller/BombshellerGoogleDrive/Chasma/NEW_DESIGNS/ForCatalog/' %>
  path_to_local_render_folder_root: <%= Rails.root.to_s + '/public/RENDERINGS/' %>

  run_remotely: false
  remote_server_uri: 'http://localhost:3000'

  collages_max_items_to_retrieve: 25
  collages_min_width_pixels: 500
  collages_min_height_pixels: 500

production:

  path_to_runner_script: <%= Rails.root.to_s + '/bin/illustrator_processing/run_AI_script.rb' %>
  path_to_extract_tags_script: <%= Rails.root.to_s + '/bin/illustrator_processing/extractTags.jsx' %>
  path_to_extract_images_script: <%= Rails.root.to_s + '/bin/illustrator_processing/extractImages.jsx' %>
  path_to_post_process_script: <%= Rails.root.to_s + '/bin/illustrator_processing/postProcess.jsx' %>
  path_to_extract_all_text_script: <%= Rails.root.to_s + '/bin/illustrator_processing/extractAllText.jsx' %>
  path_to_search_replace_script: <%= Rails.root.to_s + '/bin/illustrator_processing/searchAndReplace.jsx' %>
  path_to_image_search_replace_script: <%= Rails.root.to_s + '/bin/illustrator_processing/searchAndReplaceImages.jsx' %>
  path_to_split_text_script: <%= Rails.root.to_s + '/bin/illustrator_processing/splitText.jsx' %>
  path_to_quick_version_root: <%= Rails.root.to_s + '/versions' %>
  path_to_versions_folder: <%= Rails.root.to_s + '/public/system/versions/' %>
  path_to_collage_root: <%= Rails.root.to_s + '/collages' %>
  path_to_zombie_templates_root: <%= Rails.root.to_s + '/zombies/design_templates/' %>
  path_to_text_processing_folder: <%= Rails.root.to_s + '/working/text_processing/' %>
  path_to_remote_render_folder_root: <%= '/Volumes/krucible/Users/bombsheller/BombshellerGoogleDrive/Chasma/NEW_DESIGNS/ForCatalog/' %>
  path_to_local_render_folder_root: <%= Rails.root.to_s + '/public/RENDERINGS/' %>

  run_remotely: false
  remote_server_uri: 'http://localhost:3000'

  collages_max_items_to_retrieve: 25
  collages_min_width_pixels: 500
  collages_min_height_pixels: 500
